# Generated by Django 4.2.11 on 2024-05-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnam', models.ImageField(blank=True, null=True, upload_to='cnam_img/')),
                ('description', models.CharField(default='', max_length=30, null=True)),
                ('confirmadresse', models.CharField(default='', max_length=30, null=True)),
                ('ordonnance', models.ImageField(default='', null=True, upload_to='ordonnance_img/')),
                ('pharmacielocation', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(default='en livraison', max_length=50)),
                ('confirmationcode', models.IntegerField(blank=True, null=True)),
                ('commande', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_commande', to='appk.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('medic_image', models.ImageField(blank=True, null=True, upload_to='medic_images/')),
                ('nompharmacie', models.CharField(default='', max_length=30)),
                ('prix', models.FloatField(default=0)),
                ('temps_liv', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantite', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='appk.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Pharma_Stock_Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacie', to='appk.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('heure_ouv', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_ferm', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse', models.CharField(default='', max_length=50)),
                ('medicament', models.ManyToManyField(related_name='medicament', through='appk.Pharma_Stock_Medic', to='appk.medicament')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharma_stock_medic',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacie', to='appk.pharmacie'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
                ('prenom', models.CharField(default='', max_length=30)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('commande', models.ManyToManyField(default='', related_name='commande', through='appk.Livraison', to='appk.commande')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_livreur', to='appk.livreur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appk.patient'),
        ),
        migrations.CreateModel(
            name='Ligne_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField(default=0)),
                ('commande', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='appk.commande')),
                ('medicament', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='appk.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='cammande_reserved_medic',
            field=models.ManyToManyField(related_name='cammande_reserved_medic', through='appk.Ligne_Commande', to='appk.medicament'),
        ),
        migrations.AddField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appk.patient'),
        ),
    ]
