# Generated by Django 4.2.11 on 2024-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='role',
            field=models.CharField(default='livreur', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=30),
        ),
    ]
