# Generated by Django 4.2.11 on 2024-04-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pwd',
        ),
    ]
