# Generated by Django 4.2.11 on 2024-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0002_livreur_role_patient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='role',
            field=models.CharField(default='pharmacie', max_length=30),
        ),
    ]
