# Generated by Django 4.2.11 on 2024-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0003_pharmacie_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='nompharmacie',
            field=models.CharField(default='', max_length=30),
        ),
    ]
