# Generated by Django 4.2.11 on 2024-04-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0003_remove_patient_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='confirmadresse',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='description',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ordonnance',
            field=models.ImageField(default='', null=True, upload_to='ordonnance_img/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pharmacielocation',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
