# Generated by Django 4.2.11 on 2024-05-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0004_pharmacie_nompharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='nompharmacie',
        ),
    ]
