# Generated by Django 4.2.11 on 2024-05-04 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0005_remove_pharmacie_nompharmacie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appk.commande')),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appk.patient')),
                ('pharmacie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appk.pharmacie')),
            ],
        ),
    ]
