# Generated by Django 4.2.11 on 2024-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='role',
            field=models.CharField(blank=True, default='pharmacie', max_length=30, null=True),
        ),
    ]
