# Generated by Django 4.2.11 on 2024-05-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0007_alter_pharmacie_adresse_alter_pharmacie_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='codesecurite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
