# Generated by Django 4.2.11 on 2024-05-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0008_pharmacie_codesecurite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appk.patient'),
        ),
    ]
