# Generated by Django 4.2.11 on 2024-05-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0010_alter_commande_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appk.patient'),
        ),
    ]
