# Generated by Django 4.2.11 on 2024-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0011_alter_commande_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='adresse',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
