# Generated by Django 4.2.11 on 2024-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0012_remove_pharmacie_adresse_pharmacie_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_commande',
            name='confirmadresse',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ligne_commande',
            name='pharmacielocation',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
