# Generated by Django 4.2.11 on 2024-05-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0013_ligne_commande_confirmadresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='pharmacielocation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pharmaciecommande', to='appk.pharmacie'),
        ),
    ]
