# Generated by Django 4.2.11 on 2024-05-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0014_alter_commande_pharmacielocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='pharmacielocation',
            new_name='pharmacies',
        ),
    ]
