# Generated by Django 4.2.11 on 2024-05-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0015_rename_pharmacielocation_commande_pharmacies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='pharmacies',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pharmaciecommande', to='appk.pharmacie'),
        ),
    ]
