# Generated by Django 4.2.11 on 2024-05-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0016_alter_commande_pharmacies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='nompharmacie',
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharmaciemedic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pharmaciemedicament', to='appk.pharmacie'),
        ),
    ]
